### ISSUE TITLE
How to use gelectron ?

### ISSUE THREAD

**Issue by monok-o** [hiitiger/goverlay#10]
Hello, i have build a simple test based on the [client](https://github.com/hiitiger/gelectron/blob/master/client/src/main/electron/app-entry.ts) (https://github.com/robjullian/test-gelectron).
I run my code after opening a game and nothing happens.

Sorry for my bad english.

Thanks.

**Comment by robjullian** [comment]
Ok, thanks ! I will test this andI I says you if this don't work

**Comment by robjullian** [comment]
How I inject the dll ? when I use this code :
`
ovhook.injectProcess({
    processId: 1096,
    threadId: 10072
})
`
(I have find processId and threadId with `ovhook.getTopWindows()` (the game is Kerbal Space Program))

nothing is happening :c

I think its a problem with dll path, but I do not know where to put `n_overlay.dll`?

Thanks !

**Comment by kutu** [comment]
its looking in node's module folder
`...\gelectron\node-ovhook\build\Release\node_ovhook.node`

place n_overlay.x64.dll and n_ovhelper.x64.exe files in `...\gelectron\node-ovhook\build\Release\` folder

**Comment by robjullian** [comment]
nothing is happening :/

I think the problem comes from the PATH or the generation of the DLL

**Comment by lincolnthree** [comment]
@hiitiger I agree. I'd love to see some more docs in the README of how to use this! It seems really great but I'm having a lot of trouble getting the sample to run, or figuring out how one would use this in a new project / package it for distribution!

I imagine a lot of people would be interested in this project if they knew more about it!

**Comment by lincolnthree** [comment]
PS. This looks awesome and I'm really hoping to get into it!

**Comment by lincolnthree** [comment]
@robjullian @kutu  Have you gotten anything working? Where are you using this code?

```ovhook.injectProcess({ processId: 1096, threadId: 10072 })
ovhook.getTopWindows()```

**Comment by robjullian** [comment]
I use `ovhook.getTopWindow()` to find the "processId" and the "threadId" and then I use `ovhook.injectProcess()` with the information I found before.

**Comment by lincolnthree** [comment]
@robjullian Hmmm. But where are you getting a reference to 'ovhook' ? What kind of Object/API is it?

**Comment by kutu** [comment]
@lincolnthree you compile `node-ovhook` and `require` it

dont forget to edit index.js with
`module.exports = require('./build/Release/node_ovhook')`

**Comment by lincolnthree** [comment]
AH. OKay. Yeah I just figured that out! And!!!! I got my first overlay! It's a bit tiny, but.... WOOOO! Thank you!!! 🗡 ⚔️ 🎈 😄

**Comment by lincolnthree** [comment]
```
/// <reference types="node" />
declare module "node-ovhook" {

    export interface IProcessThread {
        processId: number, 
        threadId: number;
    }

   export interface IWindow extends IProcessThread {
        windowId: number;
        title: string;
    }

    export function getTopWindows(): IWindow[];
    export function injectProcess(process: IProcessThread): any;
}
```
