### ISSUE TITLE
Doesnt works

### ISSUE THREAD

**Issue by alananisimov** [hiitiger/goverlay#103]
i have this error after i click inject into cs go and overlay doesnt opens, what can i do to solve this problem?
`try inject Counter-Strike: Global Offensive - Direct3D 9
--------------------
 injecting {"windowId":72747310,"processId":802688,"threadId":810572,"title":"Counter-Strike: Global Offensive - Direct3D 9"}
hook pid: 802688, thread:810572OverlayMain::onClientConnect,814404
OverlayMain::_sendOverlayInit{"directMessageInput":false,"dragMode":1,"fpsPosition":1,"hotkeys":[{"alt":false,"ctrl":true,"keyCode":113,"name":"overlay.hotkey.toggleInputIntercept","passthrough":false,"shift":false},{"alt":false,"ctrl":true,"keyCode":114,"name":"app.doit","passthrough":false,"shift":false}],"processEnabled":true,"shareMemMutex":"electron-overlay-sharemem-{4C4BD948-0F75-413F-9667-AC64A7944D8E}810448-815021625","showfps":false,"type":"overlay.init","windows":[{"bufferName":"electron-overlay-810448-815021625-2-image-1","caption":{"height":40,"left":10,"right":10,"top":10},"dragBorderWidth":10,"maxHeight":1440,"maxWidth":3440,"minHeight":100,"minWidth":100,"name":"MainOverlay","nativeHandle":11274082,"rect":{"height":360,"width":640,"x":1,"y":1},"resizable":true,"transparent":false,"type":"window","windowId":2},{"bufferName":"electron-overlay-810448-815021640-3-image-2","caption":{"height":0,"left":0,"right":0,"top":0},"dragBorderWidth":0,"maxHeight":1440,"maxWidth":3440,"minHeight":100,"minWidth":100,"name":"StatusBar","nativeHandle":142345298,"rect":{"height":50,"width":200,"x":100,"y":0},"resizable":false,"transparent":false,"type":"window","windowId":3}]}
PostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook window[810448:0521/234303.525:INFO:CONSOLE(1)] "blur", source: file:///C:/Users/alan/Downloads/goverlay-master%20(1)/goverlay-master/client/dist/renderer/renderer.js (1)
PostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowPostThreadMessage to hook windowsafeInject, pid:802688, result:1OverlayMain::onClientClose,814404`

**Comment by hiitiger** [comment]
You need to sign the n_overlay*dll to inject into CSGO
