### ISSUE TITLE
how to ignore cursor-change?

### ISSUE THREAD

**Issue by MWstudio** [hiitiger/goverlay#104]
when i mouse hover on overlay in league of legends, mouse cursor change to window cursor.
i want to ignore it.

i tried remove window.webContents.on "cursor-changed", and add focusable(false) option.

**Comment by hiitiger** [comment]
@MWstudio pushed an update for this

**Comment by MWstudio** [comment]
@hiitiger i've tried to rebuild electron-overlay.node and change n_overlay.dll, but still changed-cursor
what should i do?

**Comment by KendrickFerguson** [comment]
@MWstudio is this work on exclusive full screen in league of legends? In other words, can it enable me to overlay the game while it's running? If it does, could you kindly provide me with the steps to achieve this?

**Comment by MWstudio** [comment]
> @MWstudio is this work on exclusive full screen in league of legends? In other words, can it enable me to overlay the game while it's running? If it does, could you kindly provide me with the steps to achieve this?
1. it work in full screen.
2. just follow example codes

**Comment by KendrickFerguson** [comment]
yes its work now!

**Comment by MWstudio** [comment]
updated

**Comment by rob1121** [comment]
Hello @MWstudio @hiitiger. Do you have idea how to ignore cursor-change in the draggable area? Hovering over the draggable area changes the cursor to IDC_ARROW.

**Comment by MWstudio** [comment]
@rob1121 
in "cursor-changed" sendCommand cursor null string or do not send
