### ISSUE TITLE
A terminal flashes and then disappears when goverlay attampts injecting dll to a game

### ISSUE THREAD

**Issue by yun77op** [hiitiger/goverlay#114]
It's unnecessary and annoying to the end user.

After some digging. Maybe the problem lies in https://github.com/hiitiger/goverlay/blob/master/electron-overlay/src/utils/win-utils.h#L105. Should we pass `CREATE_NO_WINDOW` to the sixth parameter?

### before
`BOOL ret = CreateProcessW(path.c_str(), (LPWSTR)(cmdLine.c_str()), NULL, NULL, FALSE, 0, NULL, dir.c_str(), &StartupInfo, &ProcInfo);`

### after
`BOOL ret = CreateProcessW(path.c_str(), (LPWSTR)(cmdLine.c_str()), NULL, NULL, FALSE, CREATE_NO_WINDOW, NULL, dir.c_str(), &StartupInfo, &ProcInfo);`

Any thoughts? Thanks.

**Comment by hiitiger** [comment]
@yun77op fixed here
https://github.com/hiitiger/goverlay/commit/3316015af72f46e46c5de7d2b96a470d0be62517
