### ISSUE TITLE
Stuttering when start overlay in League of Legends

### ISSUE THREAD

**Issue by victorhurchella** [hiitiger/goverlay#116]
In a recent League of Legends update, when start overlay, not when inject, the game suffers a strong stuttering for a few seconds, and on some computers it even crashes.
I've tested it in other games, CS2 for example, and the stuttering doesn't happen there.

Do you have any clue about what's happening?

**Comment by victorhurchella** [comment]
in this video you can see the stuttering

https://github.com/hiitiger/goverlay/assets/104106268/11fb2dec-45bb-453f-bccc-a2eb255d386f

**Comment by hiitiger** [comment]
> In a recent League of Legends update, when start overlay, not when inject, the game suffers a strong stuttering for a few seconds, and on some computers it even crashes. I've tested it in other games, CS2 for example, and the stuttering doesn't happen there.
> 
> Do you have any clue about what's happening?

thank you, will checkout
