### ISSUE TITLE
Is there a way to fetch the current  x & y position of the overlay?

### ISSUE THREAD

**Issue by rob1121** [hiitiger/goverlay#121]
I'm attempting to retrieve the updated x and y coordinates of the overlay window after moving it, but the `window.getPosition()` consistently returns the same `[x, y]` value. Any suggestions on how to accurately fetch the x and y coordinates?

**Comment by hiitiger** [comment]
if you need to get the in game postion of an overlay window, you can add an ipc message for it, pass it from ingame dll to app side thought the IPC each time a movement is done

**Comment by rob1121** [comment]
Thank you, @hiitiger. Can you direct me to the specific file I should check?

**Comment by hiitiger** [comment]
@rob1121 
https://github.com/hiitiger/sln/blob/main/n_overlay/overlay/overlay.cc#L369
https://github.com/hiitiger/sln/blob/main/n_overlay/overlay/overlay.cc#L415

here you can send back the new windows position from in-game to electron side
