### ISSUE TITLE
Hight CPU usage.

### ISSUE THREAD

**Issue by CodigosPruebas367** [hiitiger/goverlay#122]
Hello, I'm having issues with FPS in the overlay and excessive CPU usage when I add `<iframe src="https://testufo.com" width="1200" height="1200"></iframe>`  to the osr.html file.

![cpuusage](https://github.com/hiitiger/goverlay/assets/27874339/61220b63-d2e0-40d0-a514-029ad4c64587)

In the generated image that is displayed in the main window, every so often it also seems like everything is slowing down.

Is this normal, or do I need to add some configuration for it to use the GPU or something like that?

**Comment by hiitiger** [comment]
overlay needs to pass the browser's rendered content from electron to game （through share memory ）
the page is updating every frame! so every frame, it needs to copy the memory twice

this will consume a lot cpu for sure
