### ISSUE TITLE
Attaching overlay causes Debug Console to be displayed

### ISSUE THREAD

**Issue by lincolnthree** [hiitiger/goverlay#14]
Apologies for the 1000 issues. I've got things back in a semi-working state. But now when I attach the overlay to the game, a Debug Console is displayed in a separate window, and prints things like this:

```
HookApp::findGameWindow, injectWindow: 00000000
HookApp::findGameWindow, graphicsWindow: 00000000
HookApp::findGameWindow, injectWindow: 00000000
HookApp::findGameWindow, graphicsWindow: 00070612
HookApp::hookInput, 1
OverlayConnector::sendGraphicsWindowSetupInfohooked: 1
HookApp::hookD3d9, 0
HookApp::hookDXGI, 1
```

Is there a way to turn the console off or prevent this?

**Comment by hiitiger** [comment]
this is used to show some debug info in game process, it's off in release build.
You can also turn it off, checkout game-overlay\n_overlay\main.cpp, line 34, comment it to turn it off.

**Comment by lincolnthree** [comment]
Thank you! I tried commenting out that line before I posted, actually, but the log still appeared. I commented out a few more lines in various files and eventually got the log to be blank, but it was still popping up.

**Comment by vexCoder** [comment]
For people who can't find where to hide the debug console, its on `node-ovhook/src/utils.hpp` in `CreateProcessW` function add `CREATE_NO_WINDOW` on the 6th argument after the boolean argument. and then rebuild the package.

**Comment by ezequielvictor** [comment]
> For people who can't find where to hide the debug console, its on `node-ovhook/src/utils.hpp` in `CreateProcessW` function add `CREATE_NO_WINDOW` on the 6th argument after the boolean argument. and then rebuild the package.

It didn't work for me, did you do just that?

**Comment by vexCoder** [comment]
> > For people who can't find where to hide the debug console, its on `node-ovhook/src/utils.hpp` in `CreateProcessW` function add `CREATE_NO_WINDOW` on the 6th argument after the boolean argument. and then rebuild the package.
> 
> It didn't work for me, did you do just that? @vexCoder

Heres what i did, 

![Screenshot 2023-02-08 162911](https://user-images.githubusercontent.com/47610646/217786747-bfc3bfcc-e8c9-4d98-b6c3-7ee259b447db.png)
