### ISSUE TITLE
Doesnt work properly in electron 4.x

### ISSUE THREAD

**Issue by nightshadecf** [hiitiger/goverlay#25]
As the title said, electron 2.0.8 works perfectly, but electron 4.x has some render issue like scaling and positioning. Any chance you take a look at this?

**Comment by dpwolfe** [comment]
@nightshadecf Did you figure out how to adjust for this? I see the exact same issue after jumping from 2.0.8 to 9.1.1.

**Comment by hiitiger** [comment]
fixed dpi issues
