### ISSUE TITLE
Pass click from trasparency to game

### ISSUE THREAD

**Issue by CosminBd** [hiitiger/goverlay#26]
Hello!
Is it possible to pass input from the overlay to the game? I have a fullscreen HTML canvas, but as long as it is active my game won't listen to any mouse / key events.

So far I've tried: 

```
window.setIgnoreMouseEvents(true, {forward: true});
window.setFocusable(false);
```

also 

```
body {
	pointer-events: none
}
```

with no success.

Any ideas? Thanks

**Comment by CosminBd** [comment]
Got it to work by overwriting: 

`bool isAlwaysInputTransparentWindow(const std::string& name)`

in \game-overlay\n_overlay\overlay\overlay.cc

**Comment by hiitiger** [comment]
> Got it to work by overwriting:
> 
> `bool isAlwaysInputTransparentWindow(const std::string& name)`
> 
> in \game-overlay\n_overlay\overlay\overlay.cc

yeah, you can configure how each window handle will intercept or pass throught input by change this function. 

Or maybe I should make it controlled by our client app and pass it to game.

**Comment by demon-i386** [comment]
can you please provide an example for this action?
