### ISSUE TITLE
injection does not work

### ISSUE THREAD

**Issue by KCGD** [hiitiger/goverlay#59]
I downloaded and installed everything correctly and the demo ran fine but the injection itself didnt work. Everything built successfully and i moved the dlls and exes to the right places (although i did need to retarget them for a different SDK before building). idk whats wrong

when starting dx11app.exe it said it couldnt find dx11appbase.cpp in gelectron\game-overlay\demo\dx11app\src despite it being there, i tried renaming the dll to fit the missing file exactly (it didnt have any caps in there error but the file did) but no luck, it still couldnt find the file.
![image](https://user-images.githubusercontent.com/48497186/115771928-85250480-a37c-11eb-809e-54b1e8186461.png)

**Comment by dpwolfe** [comment]
@KCGD This is probably a dead issue, but anyway, I ran into this too. It looks like it could not find the FPS.png. The error is occurring from a line in the dxappbase.cpp where it's calling the D3DX11CreateShaderResourceViewFromFile, which is trying to load a file it can't find, thankfully it's printed inline there as "FPS.png". The build might not be copying any of the assets to the build output directory. You might try to manually copy that into the place where it is expecting to find it if that's the issue. Maybe it's being copied there, but your path is missing something.
