### ISSUE TITLE
Valorant

### ISSUE THREAD

**Issue by gabrielmicko** [hiitiger/goverlay#70]
I am trying the demo app with Valorant, it seems to not be working. Any thoughts why it could be? It works with demo dx app.

**Comment by gabrielmicko** [comment]
@lincolnthree @hiitiger would you mind looking at this pls?

**Comment by gabrielmicko** [comment]
After suffering a ton and with help of @honzapatCZ, figured that CS only works with -insecure flag and valorant doesn't work. It must be because of anticheat.

**Comment by dpwolfe** [comment]
@gabrielmicko I ran into the same problem with Valorant and ended up with an alternative approach that kept the app separate instead of using injection. The electron app with the overlay then rendered on top of the game. This worked for my use case, but it required me to run the game in a windowed mode.

**Comment by hiitiger** [comment]
VALORANT needs a verified sign for the binary file to inject

**Comment by gabrielmicko** [comment]
@hiitiger Can you please link some information on how do I do that?
@dpwolfe I tried the same with pure elctron and It works if the game is Windows or Fullscreen Windowed, but not when Fullscreen. :(

**Comment by hiitiger** [comment]
> @hiitiger Can you please link some information on how do I do that? @dpwolfe I tried the same with pure electron and It works if the game is Windowed or Fullscreen Windowed, but not when Fullscreen. :(

check this out
https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate

**Comment by Supertigerr** [comment]
Is there anyway to do it for free + fullscreen? 😭

**Comment by hmngwy** [comment]
@hiitiger do we need an EV certificate? We are choosing to purchase from https://www.digicert.com/order/order-1.php but we are not sure which would be sufficient for production.

**Comment by dpwolfe** [comment]
@hmngwy We started with OV, but within a couple days we wanted EV. Since we were quick about it, we were able to simply pay the difference for EV and to expedite the delivery of the hardware token. Zero interference from Windows, especially for our first VIP customers was critical. I wouldn't do it any other way now.

**Comment by hmngwy** [comment]
@dpwolfe thank you. Is the vetting process rigorous as advertised? Were there site-visit requirements? We do have an office and we are confident we can provide the requirements, but we are hoping to tie this cert to our overseas business registration (so that it may carry the brand specific name).

**Comment by honzapatCZ** [comment]
I'd just like to point out, that if you are creating cheats for Valorant, getting the OV/EV is pointless as your whole organization will get flagged by the anticheat and any DLL with signature from that org will from that point work as ban request.

**Comment by hmngwy** [comment]
> I'd just like to point out, that if you are creating cheats for Valorant, getting the OV/EV is pointless as your whole organization will get flagged by the anticheat and any DLL with signature from that org will from that point work as ban request.

Not sure if this was for me, but we're not making cheats. We're trying to make a small social platform. Just curious now how OV/EV differ in this use case. If anyone can enlighten me, that would be appreciated.

**Comment by honzapatCZ** [comment]
> > I'd just like to point out, that if you are creating cheats for Valorant, getting the OV/EV is pointless as your whole organization will get flagged by the anticheat and any DLL with signature from that org will from that point work as ban request.
> 
> Not sure if this was for me, but we're not making cheats. We're trying to make a small social platform. Just curious now how OV/EV differ in this use case. If anyone can enlighten me, that would be appreciated.

They are probably using it for normal apps to. The EV is much more verification, but it completely eliminates Windows Smart Screen, while OV might still trigger it if it uses certain more risky functions. 
Given that they are buying it for an organization the price difference is negligable, but the benefit of not having to deal with calls "My computer is showing some blue warning and I worry it might be a virus" is worth it.

**Comment by hmngwy** [comment]
Thank you @honzapatCZ this is the answer I'm looking for. Is this project known to cause the Windows Smart Screen to come up? This tells me we might want to go with EV for convenience.
