### ISSUE TITLE
Documentation for other GUI frameworks?

### ISSUE THREAD

**Issue by IcySnex** [hiitiger/goverlay#71]
The title of the project says "...for any desktop GUI like Electron, Qt, CEF and WPF".
But there is no documentation or sample project for other desktop GUI's like Qt, CEF and WPF?
How would you implement an overlay in other languages with other frameworks?

**Comment by hiitiger** [comment]
@IcySnex 
well, I did not write a complete document for that yet.
the idea is the same, 
For CEF, offscreen renderering is same as in electron.
For Qt, need to get the backing store image of a window.

**Comment by IcySnex** [comment]
What about WPF? Is it possible to completely inject an entire WPF application or a part of a WPF application into any DirectX game? And if yes, what would be the easiest way?
