### ISSUE TITLE
[UI] Displaying text

### ISSUE THREAD

**Issue by guglovich** [hiitiger/goverlay#81]
Waited for the upgrade to 0.9, saw the item about adapting the theme to the system theme. However, the fonts as in the last version I have are not congruent, grey on top of the white tab header. 

![изображение](https://user-images.githubusercontent.com/54148165/180246204-2714e3a9-acfa-48a3-b2ef-78b5998875dd.png)

**Comment by CrazyguyFPV** [comment]
I can't get it to compile using their instructions. What codebase are you using?

**Comment by guglovich** [comment]
> I can't get it to compile using their instructions. What codebase are you using?

Assembled from AUR
https://aur.archlinux.org/packages/goverlay-bin

**Comment by hiitiger** [comment]
Hi @guglovich @CrazyguyFPV 
this is a different project from what you're trying to use

**Comment by SharkRick** [comment]
> Hi @guglovich @CrazyguyFPV
> this is a different project from what you're trying to use

So what’s it take to get yours building?

**Comment by guglovich** [comment]
Strangely enough, I did make a mistake and wrote in the wrong place.
