### ISSUE TITLE
windows 11 / vs2022, overlay not working on fortnight. Possible to use discord overlay binaries?

### ISSUE THREAD

**Issue by maceip** [hiitiger/goverlay#82]
not sure what logs I can post, I saw the message about attempting hook but nothing ever happens. Anything I can upload here to help diagnose why it doesn't work?

also, would it be possible to just use the binaries produced by discord? Might be more trouble than it's worth to reverse engineer them but they work well in full screen dx3d games:

- DiscordHookHelper64.exe (supports two args : inject and offsets)
- discord_overlay_sdk_x64.dll 
          1    0 000239E0 CharEvent
          2    1 000237A0 ForwardMessage
          3    2 00023F60 ImeCancelComposition
          4    3 00023CB0 ImeCommitText
          5    4 00023D80 ImeSetComposition
          6    5 00023730 InitDxgi
          7    6 000237B0 KeyEvent
          8    7 00023B50 MouseButtonEvent
          9    8 00023C70 MouseMotionEvent
         10    9 00023780 OnPresent
         11    A 00023AC0 PointInsideClickZone
         12    B 00023C90 SetImeCompositionRangeCallback
         13    C 00023CA0 SetImeSelectionBoundsCallback
- DiscordHook64.dll

**Comment by hiitiger** [comment]
@maceip need to sign binary file to be able to inject into fortnight 😀
