### ISSUE TITLE
Demo not work

### ISSUE THREAD

**Issue by JesuisTong** [hiitiger/goverlay#83]
Hi
I try to run your demo client but failed. Here is my steps.
1. i use the `node-gyp: ^9.x` to recompile c++ addons, because i have only installed python3.
2. Then i ran the electron client successfully. Also i click the button `start overlay` and run `csgo` in steam
3. Then i input the csgo process title to **inject**, command line outputs:
```
PostThreadMessage to hook window. 
PostThreadMessage to hook window. 
PostThreadMessage to hook window. 
safeInject, pid:19808 dll:xxx\n_overlay.dll result:1
```
which means inject successfully (i guess)
4. There is no window appeared in `csgo`. Is there any step that i make wrong?

Thx a lot!

**Comment by hiitiger** [comment]
@JesuisTong CS:GO has safe mode on by default, need to turn off to inject into CS:GO

**Comment by JesuisTong** [comment]
> @JesuisTong CS:GO has safe mode on by default, need to turn off to inject into CS:GO

Unfortunately, I tried to set `Launch options` like `-untrusted`, but it did not work either.

**Comment by JesuisTong** [comment]
Finally solve the problem, it's because `dll file` does not have a `ev certificate`, but CS:GO need to run dll with cert.

`-untrusted` does not work for me, does anybody find a way to bypass the ev certificate? Thx all.

**Comment by hiitiger** [comment]
Nope, we have to sign the injected binary for CS:GO
