### ISSUE TITLE
No source files to change .dll

### ISSUE THREAD

**Issue by beermonsterdota** [hiitiger/goverlay#93]
Unfortunately, you've removed source files to compile new n_overlay.x64.dll. I need to use window with name "OverlayTip" to get simple overlay that will be always visible ontop of the game, but it have -10px offset on top and left, so it's impossible to screen of the game. 

Pretty much, all i need is this code to be compiled with latest sources for game-overlay
```void D3d11Graphics::_drawPopupTipSprite()
{
    if (overlayTipSprite_)
    {
        overlayTipSprite_->rect.x = targetWidth_ - overlayTipSprite_->rect.width;
        overlayTipSprite_->rect.y = targetHeight_ - overlayTipSprite_->rect.height;
        _drawWindowSprite(overlayTipSprite_);
    }
}
```
Also it would be great if you remove hotkey for F1 from precompiled .dlls because you can't disable that F1 acts pretty much like ctrl+F2 and triggers overlay.hotkey.toggleInputIntercept

If it's possible and you will be able to provide me just compiled .dlls, it also would be fantastic!

**Comment by hiitiger** [comment]
@beermonsterdota 

I'm plan to do refactor of source.

please checkout backup code here, https://github.com/hiitiger/game-overlay

**Comment by Tetragromaton** [comment]
up
