### ISSUE TITLE
How to ignore mouse in statusbar window?

### ISSUE THREAD

**Issue by ezequielvictor** [hiitiger/goverlay#94]
Is it possible to use the statusbar in a way that ignores mouse events as if this window were invisible?
The idea is to show a performance monitor, and that the user can click through this window

I'm using:
Electron 21.2.2 and latest goverlay version

win.setIgnoreMouseEvents(true) didn't work on overlay

**Comment by hiitiger** [comment]
change  `isAlwaysInputTransparentWindow` to configure for each window
https://github.com/hiitiger/game-overlay/blob/main/n_overlay/overlay/overlay.cc#L60
