### ISSUE TITLE
F1 Issue

### ISSUE THREAD

**Issue by Tetragromaton** [hiitiger/goverlay#98]
I've encountered an issue while in game Pressing F1 shows up main overlay while in game, and there is no any code that I found that are responsible for this, in documentation either F1 aren't mentioned so Im struggling with rebinding F1 to any other button, any advice ?

**Comment by Tetragromaton** [comment]
Also an n_overlay.dll source code are missed in this repository

**Comment by hiitiger** [comment]
checkout here

https://github.com/hiitiger/game-overlay

https://github.com/hiitiger/game-overlay/blob/main/n_overlay/overlay/uiapp.cc#L684

**Comment by Tetragromaton** [comment]
It returns 404 not found.

**Comment by hiitiger** [comment]
> It returns 404 not found.

@Tetragromaton updated
